const LAT=-41.2865,LON=174.7762,TIMEZONE="Pacific/Auckland",MANTRA_START={year:2026,month:7,day:20};
const MANTRAS=[
["Awareness","I notice my inner state without judging it."],["Awareness","Every emotion carries information for me."],["Awareness","I allow myself to feel without losing myself."],["Awareness","My feelings are real, but they are not permanent."],["Awareness","I listen to what this moment is showing me."],["Awareness","I can observe my thoughts without becoming them."],["Awareness","Awareness gives me the freedom to choose again."],
["Release","I release what no longer supports my growth."],["Release","Another person’s success expands what I believe is possible."],["Release","What belongs to others does not diminish what is available to me."],["Release","I release comparison and return to my own path."],["Release","I let go of the need to control every outcome."],["Release","I forgive myself for the ways I once tried to feel safe."],["Release","I make space for something new to emerge."],
["Trust","I trust myself to meet what comes next."],["Trust","I am safe enough to remain open."],["Trust","I trust the pace of my own becoming."],["Trust","I can move forward even when the path is not yet clear."],["Trust","What is meant for me does not require me to abandon myself."],["Trust","Life can unfold without my constant control."],["Trust","Each step reveals what I need to know next."],
["Alignment","My attention shapes the life I experience."],["Alignment","I direct my energy towards what I want to grow."],["Alignment","My actions reflect the future I am creating."],["Alignment","I choose from trust rather than fear."],["Alignment","I honour what feels honest and aligned."],["Alignment","My choices reflect the person I am becoming."],["Alignment","I bring my thoughts, values, and actions into harmony."],
["Expansion","I create from possibility, not from lack."],["Expansion","Gratitude opens my awareness to what is already here."],["Expansion","I welcome people and opportunities that align with my values."],["Expansion","Love expands when I allow it to move through me."],["Expansion","I am available for opportunities beyond what I can currently see."],["Expansion","I have the capacity to receive, grow, and contribute."],["Expansion","I am open to becoming more than I once imagined."]];
function condition(c){const m={0:"Clear sky",1:"Mainly clear",2:"Partly cloudy",3:"Overcast",45:"Fog",48:"Rime fog",51:"Light drizzle",53:"Drizzle",55:"Heavy drizzle",56:"Freezing drizzle",57:"Heavy freezing drizzle",61:"Light rain",63:"Rain",65:"Heavy rain",66:"Freezing rain",67:"Heavy freezing rain",71:"Light snow",73:"Snow",75:"Heavy snow",77:"Snow grains",80:"Light showers",81:"Rain showers",82:"Heavy showers",85:"Snow showers",86:"Heavy snow showers",95:"Thunderstorm",96:"Thunderstorm with hail",99:"Heavy thunderstorm"};return m[c]||"Weather"}
function iconKey(c){const m={0:"clear",1:"mainly",2:"partly",3:"cloud",45:"fog",48:"rime",51:"drizzle1",53:"drizzle2",55:"drizzle3",56:"freezingDrizzle",57:"freezingDrizzle",61:"rain2",63:"rain3",65:"rain4",66:"freezingRain",67:"freezingRain",71:"snow",73:"snow",75:"heavySnow",77:"snowGrains",80:"shower2",81:"shower3",82:"shower4",85:"snowShower",86:"heavySnowShower",95:"storm",96:"hail",99:"hail"};return m[c]||"cloud"}
function parts(date,options){const p=new Intl.DateTimeFormat("en-NZ",options).formatToParts(date),v={};for(const x of p)v[x.type]=x.value;return v}
function clock(date){const a=parts(date,{timeZone:TIMEZONE,weekday:"long",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}),n=parts(date,{timeZone:TIMEZONE,year:"numeric",month:"numeric",day:"numeric"});return{hour:Number(a.hour),minute:Number(a.minute),year:Number(n.year),month:Number(n.month),day:Number(n.day),dateText:a.weekday+", "+a.day+" "+a.month+" "+a.year}}
function weekday(v){return new Intl.DateTimeFormat("en-NZ",{timeZone:"UTC",weekday:"short"}).format(new Date(v+"T12:00:00Z"))}
const LUNAR_DAYS=["","初一","初二","初三","初四","初五","初六","初七","初八","初九","初十","十一","十二","十三","十四","十五","十六","十七","十八","十九","二十","廿一","廿二","廿三","廿四","廿五","廿六","廿七","廿八","廿九","三十"];
function lunarParts(date){const p=new Intl.DateTimeFormat("zh-CN-u-ca-chinese",{timeZone:TIMEZONE,month:"long",day:"numeric"}).formatToParts(date),v={month:"",day:0};for(const x of p){if(x.type==="month")v.month=x.value;if(x.type==="day")v.day=Number(x.value)}return v}
function lunarLabel(date){const l=lunarParts(date);if(!l.day)return"农历";if(l.day===1)return l.month+"初一";return LUNAR_DAYS[l.day]||"农历"}
function calendarData(now){const c=clock(now),year=c.year,monthIndex=c.month-1,first=new Date(Date.UTC(year,monthIndex,1,12)).getUTCDay(),days=new Date(Date.UTC(year,monthIndex+1,0,12)).getUTCDate(),previousDays=new Date(Date.UTC(year,monthIndex,0,12)).getUTCDate(),cells=[];let day=1,next=1;for(let i=0;i<42;i++){let date,solar,muted;if(i<first){solar=previousDays-first+i+1;date=new Date(Date.UTC(year,monthIndex-1,solar,12));muted=true}else if(day<=days){solar=day;date=new Date(Date.UTC(year,monthIndex,solar,12));muted=false;day++}else{solar=next;date=new Date(Date.UTC(year,monthIndex+1,solar,12));muted=true;next++}cells.push({solar:solar,lunar:lunarLabel(date),muted:muted,today:!muted&&solar===c.day})}const title=new Intl.DateTimeFormat("en-NZ",{timeZone:TIMEZONE,month:"long",year:"numeric"}).format(now);return{monthTitle:title,cells:cells}}
function mantraData(now){const c=clock(now),today=Date.UTC(c.year,c.month-1,c.day),start=Date.UTC(MANTRA_START.year,MANTRA_START.month-1,MANTRA_START.day);let diff=Math.floor((today-start)/86400000);diff=((diff%35)+35)%35;const item=MANTRAS[diff];return{day:diff+1,week:Math.floor(diff/7)+1,theme:item[0],text:item[1]}}
function time(v){return String(v||"").slice(11,16)}
function updated(date){return new Intl.DateTimeFormat("en-NZ",{timeZone:TIMEZONE,hour:"2-digit",minute:"2-digit",hour12:false}).format(date)}
function compass(deg){const names=["N","NE","E","SE","S","SW","W","NW"];return names[Math.round((((deg%360)+360)%360)/45)%8]}
function arrowRotation(deg){return(Math.round((((deg%360)+360)%360)/45)%8)*45}
module.exports=async function handler(req,res){try{const url="https://api.open-meteo.com/v1/forecast?latitude="+LAT+"&longitude="+LON+"&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,sunrise,sunset,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant&forecast_days=6&timezone="+encodeURIComponent(TIMEZONE);const r=await fetch(url);if(!r.ok)throw new Error("Weather service error");const w=await r.json(),forecast=[];for(let i=1;i<=5;i++){const deg=Math.round(w.daily.wind_direction_10m_dominant[i]);forecast.push({date:w.daily.time[i],day:weekday(w.daily.time[i]),condition:condition(w.daily.weather_code[i]),icon:iconKey(w.daily.weather_code[i]),high:Math.round(w.daily.temperature_2m_max[i]),low:Math.round(w.daily.temperature_2m_min[i]),windDirection:compass(deg),arrowRotation:arrowRotation(deg),wind:Math.round(w.daily.wind_speed_10m_max[i]),gust:Math.round(w.daily.wind_gusts_10m_max[i])})}const now=new Date();res.setHeader("Cache-Control","s-maxage=900, stale-while-revalidate=1800");res.status(200).json({clock:clock(now),current:{temperature:Math.round(w.current.temperature_2m),humidity:Math.round(w.current.relative_humidity_2m),wind:Math.round(w.current.wind_speed_10m),condition:condition(w.current.weather_code),icon:iconKey(w.current.weather_code)},sunrise:time(w.daily.sunrise[0]),sunset:time(w.daily.sunset[0]),forecast:forecast,calendar:calendarData(now),mantra:mantraData(now),updated:updated(now)})}catch(e){res.status(502).json({error:"Weather data unavailable"})}}
